CREATE TABLE IF NOT EXISTS cursos(
    id BIGINT AUTO_INCREMENT,
    nombre VARCHAR(150) NOT NULL ,
    categoria VARCHAR(150) NOT NULL,
    PRIMARY KEY(id)

)ENGINE=InnoDB DEFAULT CHARSET=UTF8;